run:
  mode: train_only
  note: eval_regime_adapt_m3fast
  n_runs: 1
  from_session: null
  from_run: 1
  generate_figures: false
data:
  provider_uri: ~/.qlib/qlib_data/cn_data
  region: cn
  instruments: csi1000
  benchmark: SH000852
  handler:
    class: Alpha158RegimeTechnical
    module_path: backtest.features.regime
    start_time: '2020-02-03'
    end_time: '2026-07-31'
    fit_start_time: '2020-02-03'
    fit_end_time: '2020-08-03'
    feature_groups:
    - range
    infer_processors:
    - class: ProcessInf
    label:
    - - Ref($close, -41)/Ref($close, -1)-1
    - - LABEL0
    learn_processors:
    - class: DropnaLabel
    - class: CSRankNorm
      kwargs:
        fields_group: label
    regime_csv: /Users/yuxianqi/Project/qlib_exp/backtest/configs/regime-adapt/regime_features_v1.csv
segments:
  train:
  - '2004-01-02'
  - '2020-07-31'
  valid:
  - '2020-08-03'
  - '2026-07-31'
  test:
  - '2020-08-03'
  - '2026-07-31'
model:
  class: LGBModel
  module_path: qlib.contrib.model.gbdt
  kwargs:
    loss: mse
    seed: 42
