# EXPERIMENT_STANDARD v1.0 | exp: baseline/b0-m | seed 1000
# python backtest/scripts/run_backtest.py --config b0_csi300_lgbm_s1000.yaml
run:
  mode: train_backtest
  note: b0_csi300_lgbm_s1000
  n_runs: 1
  from_session: null
  from_run: 1
  generate_figures: false
data:
  provider_uri: ~/.qlib/qlib_data/cn_data
  region: cn
  instruments: csi300
  benchmark: SH000300
  handler:
    class: Alpha158
    module_path: qlib.contrib.data.handler
    start_time: '2003-01-02'
    end_time: '2026-07-16'
    fit_start_time: '2006-01-02'
    fit_end_time: '2020-01-10'
    infer_processors:
    - class: ProcessInf
segments:
  train:
  - '2006-01-02'
  - '2020-01-10'
  valid:
  - '2020-01-13'
  - '2021-07-15'
  test:
  - '2021-07-16'
  - '2026-07-16'
model:
  class: LGBModel
  module_path: qlib.contrib.model.gbdt
  kwargs:
    loss: mse
    colsample_bytree: 0.8879
    learning_rate: 0.2
    subsample: 0.8789
    lambda_l1: 205.6999
    lambda_l2: 580.9768
    max_depth: 8
    num_leaves: 210
    num_threads: 8
    seed: 1000
strategy:
  class: TopkDropoutStrategy
  module_path: qlib.contrib.strategy.signal_strategy
  topk: 10
  n_drop: 2
  kwargs:
    hold_thresh: 1
    risk_degree: 0.95
    only_tradable: false
    forbid_all_trade_at_limit: false
backtest:
  account: 1000000
  exchange_kwargs:
    freq: day
    deal_price: close
    limit_threshold: 0.095
    open_cost: 0.00021
    close_cost: 0.00071
    min_cost: 5
    trade_unit: 100
